config/routes.rb
Sprechensiescience::Application.routes.draw do
  resources :episodes
  get 'privacy' => 'pages#privacy', as: :privacy
  root 'pages#index'
end

app/models/episode.rb
class Episode < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < PublicController
  expose(:episodes){ Episode.order("id DESC").scoped{} }
  expose(:episode, attributes: :episode_params)

private
  def episode_params
    params.require(:episode).permit(
      :name,
      :description,
      :video,
      :icon
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < PublicController
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/episodes/show.html.haml
#main
  #episode
    %iframe{allowfullscreen: "", frameborder: "0", height: "720", src: "#{episode.video}", width: "960"}
    .info
      .screenshot
        = link_to episode_path(episode.id, :autoplay => true) do 
          %img{alt: episode.name, height: "125", src: "/episodes/#{episode.icon}", width: "200"}/
      %h1
        %span.position # #{episode.id}
        = episode.name
      .description= episode.description
      .watch
        = link_to episode_path(episode.id, :autoplay => true), class: 'play_video pretty_button' do
          Click to Play Video ▶
      .social

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %title Sprechensiescience
    %meta{content: "", name: "description"}/
    %meta{content: "", name: "keywords"}/
    %script{src: "http://cdn.sublimevideo.net/js/3s7oes9q.js", type: "text/javascript"}
    = stylesheet_link_tag    "/app.css", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #top
      .logo
        = link_to root_path do
          %img{alt: "Sprechensiescience - Screencasts", height: "56", src: "/assets/logo.png", width: "423"}/
      -#%ul.subscribe.horizontal
        %li
          %a{href: "http://phobos.apple.com/WebObjects/MZStore.woa/wa/viewPodcast?id=218282043"}
            %img{alt: "Itunes", height: "34", src: "/assets/icons/itunes-ea9253b9b183d9788bef2cdfe326f38e.png", width: "34"}/
          %span.name watch on iTunes
        %li
          %a{href: "http://twitter.com/railscasts"}
            %img{alt: "Twitter", height: "34", src: "/assets/icons/twitter-f0259ab802804e09139fb29f47678b2c.png", width: "34"}/
          %span.name follow on Twitter
        %li
          %a{href: "http://www.facebook.com/pages/railscasts/197415140659"}
            %img{alt: "Facebook", height: "34", src: "/assets/icons/facebook-0ab869e74b54d9c58f33c1c75264d869.png", width: "34"}/
          %span.name follow on Facebook
        %li
          %a{href: "http://feeds.feedburner.com/railscasts"}
            %img{alt: "Rss", height: "34", src: "/assets/icons/rss-04cb962054caa957a6fa3924c48594d8.png", width: "34"}/
          %span.name subscribe to RSS feed
    -#nav_bar
      %ul.nav.horizontal
        %li Browse Episodes
        %li
          %a{href: "/pro"} RailsCasts Pro
        %li
          %a{href: "/notifications"} Notifications
        %li
          %a{href: "/about"} About
        %li
          %a{href: "/feedback"} Feedback
      %form{"accept-charset" => "UTF-8", action: "http://railscasts.com/episodes", method: "get"}
        %div{style: "margin:0;padding:0;display:inline"}
          %input{name: "utf8", type: "hidden", value: "✓"}/
        %input#search{name: "search", size: "35", type: "text"}/
        %input{type: "submit", value: "Search Episodes"}/
    #announcement_banner
      %p Please read for an updated status on SprechenSieScience:
    #main
      = yield
    #footer
      .inner
        \©2013 - #{Date.today.year } SprechenSieScience -
        = link_to 'Privacy Policy', privacy_path
        \- Hosted by
        %a{href: "http://www.circletechfl.com", :target => '_blank'} Circle Tech Fl
    / Google Analytics
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-47768928-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

app/views/pages/index.html.haml
.content
  .side
    -#.episode_views
      View:
      %span.view
        %img{alt: "Full", height: "10", src: "/assets/views/full-0788b5fc76d8a1d653004ad44fbf31e5.png", width: "15"}/
      %span.view
        %a{href: "/?view=list", title: "List View"}
          %img{alt: "List", height: "10", src: "/assets/views/list-f3b69d30cdb1ef80b12126c5dbd3fc7a.png", width: "14"}/
      %span.view
        %a{href: "/?view=grid", title: "Grid View"}
          %img{alt: "Grid", height: "10", src: "/assets/views/grid-119e56c5d75467c317c16c5c6fef94da.png", width: "11"}/
    -#.search_option
      %h2 Types
      %ul
        %li
          %a{href: "/?type=free"} Free Episodes
        %li
          %a{href: "/?type=pro"} Pro Episodes
        %li
          %a{href: "/?type=revised"} Revised Episodes
    -#.search_option
      %h2 Categories
      %ul
        %li
          %a{href: "/?tag_id=2"} Active Record
        %li
          %a{href: "/?tag_id=19"} Active Resource
        %li
          %a{href: "/?tag_id=3"} Active Support
        %li
          %a{href: "/?tag_id=9"} Administration
        %li
          %a{href: "/?tag_id=11"} Ajax
        %li
          %a{href: "/?tag_id=37"} APIs
        %li
          %a{href: "/?tag_id=25"} Authentication
        %li
          %a{href: "/?tag_id=26"} Authorization
        %li
          %a{href: "/?tag_id=32"} Background Jobs
        %li
          %a{href: "/?tag_id=18"} Caching
        %li
          %a{href: "/?tag_id=39"} Code Walkthrough
        %li
          %a{href: "/?tag_id=8"} Controllers
        %li
          %a{href: "/?tag_id=10"} Debugging
        %li
          %a{href: "/?tag_id=21"} Deployment
        %li
          %a{href: "/?tag_id=23"} eCommerce
        %li
          %a{href: "/?tag_id=15"} Forms
        %li
          %a{href: "/?tag_id=28"} Mailing
        %li
          %a{href: "/?tag_id=16"} Models
        %li
          %a{href: "/?tag_id=1"} Performance
        %li
          %a{href: "/?tag_id=13"} Plugins
        %li
          %a{href: "/?tag_id=33"} Production
        %li
          %a{href: "/?tag_id=35"} Rack
        %li
          %a{href: "/?tag_id=17"} Rails 2.0
        %li
          %a{href: "/?tag_id=20"} Rails 2.1
        %li
          %a{href: "/?tag_id=22"} Rails 2.2
        %li
          %a{href: "/?tag_id=24"} Rails 2.3
        %li
          %a{href: "/?tag_id=27"} Rails 3.0
        %li
          %a{href: "/?tag_id=31"} Rails 3.1
        %li
          %a{href: "/?tag_id=34"} Rails 3.2
        %li
          %a{href: "/?tag_id=38"} Rails 4.0
        %li
          %a{href: "/?tag_id=6"} Refactoring
        %li
          %a{href: "/?tag_id=14"} Routing
        %li
          %a{href: "/?tag_id=30"} Search
        %li
          %a{href: "/?tag_id=5"} Security
        %li
          %a{href: "/?tag_id=7"} Testing
        %li
          %a{href: "/?tag_id=12"} Tools
        %li
          %a{href: "/?tag_id=4"} Views
    -#.banner
      %a{href: "https://www.digitalocean.com/?utm_source=railscasts.com"}
        %img{alt: "Digital Ocean", src: "/static/sponsors/digitalocean.png"}/
  .episodes
    .full
      - episodes.each do |e|
        .episode{id: "episode_#{e.id}"}
          .screenshot
            = link_to episode_path(e.id) do
              %img{alt: "Foundation", height: "125", src: "/episodes/#{e.icon}", width: "200"}/
          .main
            .info
              %span.number Episode # #{e.id}
              \–
              %span.published_at= e.created_at.strftime('%D')
            %h2
              = link_to episode_path(e.id) do
                = e.name.titleize
            .description
              = e.description
            .watch
              =  link_to 'Watch Episode', episode_path(e.id), class: 'pretty_button'
          .clear

app/views/pages/privacy.html.haml
.main
  .content
    %h1.content Privacy Policy
    #privacy.content
      %p SprechenSieScience is committed to protecting our users' privacy. This statement is meant to inform our users of how we define, gather and utilize personally identifiable information. We will take reasonable steps to protect user privacy consistent within the guidelines set forth in this policy and the law. By using this site, you consent to the following privacy policy.
      %p
        This policy was last modified on
        = succeed "." do
          %strong Feb 03, 2014
      %h2 Personal Information
      %p Cookies are used to store information about your current session and other preferences. This information may be used to track user progress and to offer a more personalized experience. Cookies can be disabled or cleared in your web browser settings.
      %h2 Third Parties
      %p We do not sell, trade, or otherwise transfer user information to outside parties. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.
      %p Any linked, third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites.